const path = require('path');
const vscode = require('vscode');

/**
 * Guard for executable paths that the extension spawns (the LSP server and
 * synesis-coder).
 *
 * Threat model: a Synesis project folder is untrusted data — it circulates
 * between researchers and is generated by synesis-coder. The executable-path
 * settings are machine-scoped in package.json, so a workspace's
 * .vscode/settings.json cannot override them. This module is the defense in
 * depth on top of that scope:
 *
 *   - refuses an executable that resolves to inside the open workspace (a
 *     bundled .exe/.bat shipped inside a project ZIP), and
 *   - in an untrusted workspace, forces the built-in default, ignoring any
 *     configured path regardless of where it came from.
 */

function stripQuotes(value) {
    return String(value || '').trim()
        .replace(/^"(.*)"$/, '$1')
        .replace(/^'(.*)'$/, '$1');
}

function isWithin(child, parent) {
    const rel = path.relative(parent, child);
    return rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel);
}

/**
 * Returns true if `execPath` resolves to a file inside any workspace folder.
 * A bare command name (resolved via PATH, e.g. "synesis-lsp") is not a path and
 * is never considered inside the workspace.
 */
function resolvesInsideWorkspace(execPath) {
    const cleaned = stripQuotes(execPath);
    // Bare command (no separator): resolved from PATH, not from the workspace.
    if (!cleaned.includes('/') && !cleaned.includes('\\')) {
        return false;
    }
    const folders = vscode.workspace.workspaceFolders || [];
    if (folders.length === 0) {
        return false;
    }
    const abs = path.resolve(cleaned);
    return folders.some(folder => {
        const root = folder.uri && folder.uri.fsPath;
        return root && (abs === path.resolve(root) || isWithin(abs, root));
    });
}

/**
 * Resolves the executable to actually spawn.
 *
 * @param {string} configuredPath value read from configuration
 * @param {string} defaultCommand built-in default (a bare PATH command)
 * @returns {{ command: string, forcedDefault: boolean, reason?: string }}
 */
function resolveExecutable(configuredPath, defaultCommand) {
    const cleaned = stripQuotes(configuredPath) || defaultCommand;

    if (!vscode.workspace.isTrusted) {
        if (cleaned !== defaultCommand) {
            return {
                command: defaultCommand,
                forcedDefault: true,
                reason: 'workspace is not trusted; using built-in default executable'
            };
        }
        return { command: defaultCommand, forcedDefault: false };
    }

    if (resolvesInsideWorkspace(cleaned)) {
        return {
            command: defaultCommand,
            forcedDefault: true,
            reason: 'configured executable resolves inside the workspace; using built-in default'
        };
    }

    return { command: cleaned, forcedDefault: false };
}

module.exports = { resolveExecutable, resolvesInsideWorkspace, stripQuotes };
